/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CustomTourRouteImport } from './routes/custom-tour'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminPackagesRouteImport } from './routes/admin/packages'
import { Route as PackagesIndexRouteImport } from './routes/packages.index'
import { Route as PackagesSlugRouteImport } from './routes/packages.$slug'
import { Route as AdminPackagesIndexRouteImport } from './routes/admin/packages.index'
import { Route as AdminPackagesCreateRouteImport } from './routes/admin/packages.create'
import { Route as AdminPackagesIdEditRouteImport } from './routes/admin/packages.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomTourRoute = CustomTourRouteImport.update({
  id: '/custom-tour',
  path: '/custom-tour',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPackagesRoute = AdminPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AdminRoute,
} as any)
const PackagesIndexRoute = PackagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PackagesRoute,
} as any)
const PackagesSlugRoute = PackagesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PackagesRoute,
} as any)
const AdminPackagesIndexRoute = AdminPackagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPackagesRoute,
} as any)
const AdminPackagesCreateRoute = AdminPackagesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminPackagesRoute,
} as any)
const AdminPackagesIdEditRoute = AdminPackagesIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminPackagesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/custom-tour': typeof CustomTourRoute
  '/login': typeof LoginRoute
  '/packages': typeof PackagesRouteWithChildren
  '/signup': typeof SignupRoute
  '/admin/packages': typeof AdminPackagesRouteWithChildren
  '/packages/$slug': typeof PackagesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/packages/': typeof PackagesIndexRoute
  '/admin/packages/create': typeof AdminPackagesCreateRoute
  '/admin/packages/': typeof AdminPackagesIndexRoute
  '/admin/packages/$id/edit': typeof AdminPackagesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/custom-tour': typeof CustomTourRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/packages/$slug': typeof PackagesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/packages': typeof PackagesIndexRoute
  '/admin/packages/create': typeof AdminPackagesCreateRoute
  '/admin/packages': typeof AdminPackagesIndexRoute
  '/admin/packages/$id/edit': typeof AdminPackagesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/custom-tour': typeof CustomTourRoute
  '/login': typeof LoginRoute
  '/packages': typeof PackagesRouteWithChildren
  '/signup': typeof SignupRoute
  '/admin/packages': typeof AdminPackagesRouteWithChildren
  '/packages/$slug': typeof PackagesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/packages/': typeof PackagesIndexRoute
  '/admin/packages/create': typeof AdminPackagesCreateRoute
  '/admin/packages/': typeof AdminPackagesIndexRoute
  '/admin/packages/$id/edit': typeof AdminPackagesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/custom-tour'
    | '/login'
    | '/packages'
    | '/signup'
    | '/admin/packages'
    | '/packages/$slug'
    | '/admin/'
    | '/packages/'
    | '/admin/packages/create'
    | '/admin/packages/'
    | '/admin/packages/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/custom-tour'
    | '/login'
    | '/signup'
    | '/packages/$slug'
    | '/admin'
    | '/packages'
    | '/admin/packages/create'
    | '/admin/packages'
    | '/admin/packages/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/custom-tour'
    | '/login'
    | '/packages'
    | '/signup'
    | '/admin/packages'
    | '/packages/$slug'
    | '/admin/'
    | '/packages/'
    | '/admin/packages/create'
    | '/admin/packages/'
    | '/admin/packages/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  CustomTourRoute: typeof CustomTourRoute
  LoginRoute: typeof LoginRoute
  PackagesRoute: typeof PackagesRouteWithChildren
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-tour': {
      id: '/custom-tour'
      path: '/custom-tour'
      fullPath: '/custom-tour'
      preLoaderRoute: typeof CustomTourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/packages': {
      id: '/admin/packages'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AdminPackagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/packages/': {
      id: '/packages/'
      path: '/'
      fullPath: '/packages/'
      preLoaderRoute: typeof PackagesIndexRouteImport
      parentRoute: typeof PackagesRoute
    }
    '/packages/$slug': {
      id: '/packages/$slug'
      path: '/$slug'
      fullPath: '/packages/$slug'
      preLoaderRoute: typeof PackagesSlugRouteImport
      parentRoute: typeof PackagesRoute
    }
    '/admin/packages/': {
      id: '/admin/packages/'
      path: '/'
      fullPath: '/admin/packages/'
      preLoaderRoute: typeof AdminPackagesIndexRouteImport
      parentRoute: typeof AdminPackagesRoute
    }
    '/admin/packages/create': {
      id: '/admin/packages/create'
      path: '/create'
      fullPath: '/admin/packages/create'
      preLoaderRoute: typeof AdminPackagesCreateRouteImport
      parentRoute: typeof AdminPackagesRoute
    }
    '/admin/packages/$id/edit': {
      id: '/admin/packages/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/packages/$id/edit'
      preLoaderRoute: typeof AdminPackagesIdEditRouteImport
      parentRoute: typeof AdminPackagesRoute
    }
  }
}

interface AdminPackagesRouteChildren {
  AdminPackagesCreateRoute: typeof AdminPackagesCreateRoute
  AdminPackagesIndexRoute: typeof AdminPackagesIndexRoute
  AdminPackagesIdEditRoute: typeof AdminPackagesIdEditRoute
}

const AdminPackagesRouteChildren: AdminPackagesRouteChildren = {
  AdminPackagesCreateRoute: AdminPackagesCreateRoute,
  AdminPackagesIndexRoute: AdminPackagesIndexRoute,
  AdminPackagesIdEditRoute: AdminPackagesIdEditRoute,
}

const AdminPackagesRouteWithChildren = AdminPackagesRoute._addFileChildren(
  AdminPackagesRouteChildren,
)

interface AdminRouteChildren {
  AdminPackagesRoute: typeof AdminPackagesRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPackagesRoute: AdminPackagesRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PackagesRouteChildren {
  PackagesSlugRoute: typeof PackagesSlugRoute
  PackagesIndexRoute: typeof PackagesIndexRoute
}

const PackagesRouteChildren: PackagesRouteChildren = {
  PackagesSlugRoute: PackagesSlugRoute,
  PackagesIndexRoute: PackagesIndexRoute,
}

const PackagesRouteWithChildren = PackagesRoute._addFileChildren(
  PackagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  CustomTourRoute: CustomTourRoute,
  LoginRoute: LoginRoute,
  PackagesRoute: PackagesRouteWithChildren,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
